src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="N'oubliez pas de mettre une photo!")
     * @Assert\File(mimeTypes={"image/png"})
     */
    private $photo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disponible;

    /**
     * @ORM\Column(type="integer")
     */
    private $stock;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeProduit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $typeProduit_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="produit", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PanierProduits", mappedBy="produit", cascade={"persist", "remove"})
     */
    private $panierProduits;

    public function __construct()
    {
        $this->panierProduits = new ArrayCollection();
	    $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix()
    {
        return $this->prix;
    }

    public function setPrix($prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDisponible(): ?bool
    {
        return $this->disponible;
    }

    public function setDisponible(bool $disponible): self
    {
        $this->disponible = $disponible;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getTypeProduitId(): ?TypeProduit
    {
        return $this->typeProduit_id;
    }

    public function setTypeProduitId(?TypeProduit $typeProduit_id): self
    {
        $this->typeProduit_id = $typeProduit_id;

        return $this;
    }

    /**
     * @return Collection|PanierProduits[]
     */
    public function getPanierProduits(): Collection
    {
        return $this->panierProduits;
    }

    public function addPanierProduit(PanierProduits $panierProduit): self
    {
        if (!$this->panierProduits->contains($panierProduit)) {
            $this->panierProduits[] = $panierProduit;
            $panierProduit->setProduit($this);
        }

        return $this;
    }

    public function removePanierProduit(PanierProduits $panierProduit): self
    {
        if ($this->panierProduits->contains($panierProduit)) {
            $this->panierProduits->removeElement($panierProduit);
            // set the owning side to null (unless already changed)
            if ($panierProduit->getProduit() === $this) {
                $panierProduit->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProduit($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProduit() === $this) {
                $comment->setProduit(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\TypeProduit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prix')
            ->add('photo', FileType::class, array(
            	'label'=>'Photo au format PNG'
            ))
            ->add('disponible')
            ->add('stock')
            ->add('typeProduit_id', EntityType::class, array(
            	'class' => TypeProduit::class,
	            'choice_label' => 'libelle',
	            'required' => true,
	            'expanded'=>true,
	            'multiple'=>false,
	            'by_reference'=>false
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\PanierProduits;
use App\Entity\Produit;
use App\Entity\TypeProduit;
use App\Form\CommentType;
use App\Form\ProduitType;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ProduitController
 * @Security("is_granted('ROLE_USER') or is_granted('ROLE_ADMIN')")
 * @package App\Controller
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/produits/show",name="Produit.show")
     */
    public function showProduits(SessionInterface $session,PaginatorInterface$paginator, Request $request){
        if ($session->get('categorie')!= 'All'){
            dump($session->get('categorie'));
            $produits=$paginator->paginate($this->getDoctrine()->getRepository(Produit::class)->findAllByCategorie($session->get('categorie')),
                $request->query->getInt('page', 1),9
            );
        }else{
            $produits=$paginator->paginate($this->getDoctrine()->getRepository(Produit::class)->findAll(),
                $request->query->getInt('page', 1),9
            );
        }
		$panier = $this->getUser()->getPanier();
        $montant=0;
        foreach ($panier->getPanierProduits() as $produit){
            $montant=$montant+($produit->getProduit()->getPrix())*($produit->getQuantity());
        }

        return $this->render("produit/showProduits.html.twig", [
        	"produits" => $produits,
	        'panier' => $panier,
            'montant'=>$montant
        ]);
    }

	/**
	 * @Route("/produits/viewDetails/{id}", name="Produit.viewDetails", requirements={"id"="\d+"})
	 * @param Produit $produit
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function detailsProduits(Produit $produit) {
		$comment = new Comment();
		$form = $this->createForm(CommentType::class, $comment);

		return $this->render('produit/viewDetails.html.twig',[
			'produit' => $produit,
			'form' => $form->createView(),
            'user'=>$this->getUser()
		]);
    }

	/**
	 * @Route("/produits/remove/{id}", name="Produit.remove", requirements={"id"="\d+"})
	 * @IsGranted("ROLE_ADMIN")
	 * @param Produit $produit
	 * @return \Symfony\Component\HttpFoundation\RedirectResponse
	 */
	public function removeProduit(ObjectManager $manager, Produit $produit) {

		$manager->remove($produit);
		$manager->flush();
		return $this->redirectToRoute('Produit.show');
    }

	/**
	 * @Route("/produits/add", name="Produit.add")
	 * @isGranted("ROLE_ADMIN")
	 * @param ObjectManager $manager
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
	 */
	public function addProduit(ObjectManager $manager, Request $request) {
		$produit = new Produit();
		$form = $this->createForm(ProduitType::class, $produit);

		$form->handleRequest($request);
		if ($form->isSubmitted() and $form->isValid()){
			/** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
			$file = $form->get('photo')->getData();

			$fileName = $this->generateUniqueFilename().'.'.$file->guessExtension();

			try{
				$file->move(
					$this->getParameter('photos_directory'),
					$fileName
				);
			}catch (FileException $e){
				throw $e;
			}

			$produit->setPhoto($fileName);

			$manager->persist($produit);
			$manager->flush();
			return $this->redirectToRoute('Produit.show');
		}

		return $this->render('produit/addProduit.html.twig', [
			'form'=>$form->createView()
		]);
    }

    private function generateUniqueFilename(){
		return md5(uniqid());
    }

	/**
	 * @Route("/produits/show/by/type", name="Produit.showByType")
	 * @param ObjectManager $manager
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
    public function showProduitsByType(ObjectManager $manager, Request $request, SessionInterface $session){
		$typesProduits = $manager->getRepository(TypeProduit::class)->findAll();
		$produits = $manager->getRepository(Produit::class)->findAll();
		$produits_to_show = $produits;
	    if (isset($_POST['submit'])) {
	    	$produits_to_show=array();
		    if (isset($_POST['typeCategorie'])) {
			    $categorie_actuelle = $_POST['typeCategorie'];
			    if ($categorie_actuelle != -1) {
			    	$cat = $manager->getRepository(TypeProduit::class)->find($categorie_actuelle);
				    $session->clear();
				    $session->set('categorie', $categorie_actuelle);
			        foreach ($produits as $produit){
			        	if ($produit->getTypeProduitId()->getId() == $cat->getId()){
			        		$produits_to_show[] = $produit;
				        }
			        }
			    }else{
			    	$produits_to_show = $produits;
				    $session->clear();
				    $session->set('categorie', 'All');
			    }
		    }
	    }
	    return $this->render('produit/filter_produits.html.twig', [
			'typesProduits' => $typesProduits,
		    'produits' =>$produits_to_show
		]);
    }

    /**
     * @Route("/produit/incremente/{id}",name="produit.incremente",  requirements={"id"="\d+"})
     * @IsGranted("ROLE_ADMIN")
     * @param Produit $produit
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     *
     */
    public function incrementeProduit(ObjectManager $manager, Produit $produit){
        $produit->setStock($produit->getStock()+1);
        $manager->persist($produit);
        $manager->flush();
        return $this->redirectToRoute('Produit.show');
    }

    /**
     * @Route("/produit/decremente/{id}",name="produit.decremente",  requirements={"id"="\d+"})
     * @IsGranted("ROLE_ADMIN")
     * @param Produit $produit
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function decrementeProduit(ObjectManager $manager, Produit $produit){
        if ($produit->getStock()>0){
            $produit->setStock($produit->getStock()-1);
            $manager->persist($produit);
            $manager->flush();
        }
        return $this->redirectToRoute('Produit.show');
    }
}

templates/produit/addProduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ajouter produit
{% endblock %}

{% block header %}
<h1>Ajouter un nouveau produit</h1>
{% endblock %}

{% block body %}
    <div style="margin-bottom: 5em;">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-success">Ajouter</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/produit/filter_produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}Filtre{% endblock %}

{% block header %}
<h1>Voir produits par catégorie</h1>
{% endblock %}

{% block body %}
   <form action="{{ path('Produit.showByType') }}" method="post" class="mb-3 justify-content-center form-inline text-center">
        <div class="bd-example">
            <div class="custom-control custom-radio custom-control-inline">
                <input type="radio" id="allTypes" name="typeCategorie" class="custom-control-input" checked="checked" value="-1">
                <label class="custom-control-label" for="allTypes"><strong>Tous</strong></label>
            </div>
            {% for categorie in typesProduits %}
                <div class="custom-control custom-radio custom-control-inline">
                    <input type="radio" id="{{ categorie.id }}" value="{{ categorie.id }}" name="typeCategorie" class="custom-control-input">
                    <label class="custom-control-label" for="{{ categorie.id }}"><strong>{{ categorie.libelle }}</strong></label>
                </div>
            {% endfor %}
        </div>
        <button type="submit" name="submit" class="btn btn-info">Valider</button>
    </form>

    <div class="row" style="margin-bottom: 5em;">
        <div class="col-12 col-sm-12 col-lg-12">
            <div class="table-responsive">
                <table class="table">
                    {% if produits is not empty %}
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Nom</th>
                            <th scope="col">Prix</th>
                            <th scope="col" class="text-center">Photo</th>
                            <th scope="col" class="text-center">Type de Produit</th>
                            <th scope="col" class="text-center">Stock</th>
                        </tr>
                        </thead>
                    {% else %}
                        <tr><th colspan="7" class="text-center">Pas de produit disponile</th></tr>
                    {% endif %}
                    <tbody>
                    {% for produit in produits %}
                        <tr>
                            <th scope="row"><a href="{{ path('Produit.viewDetails', {id: produit.id}) }}">{{ produit.nom }}</a></th>
                            <td>{{ produit.prix }}</td>
                            <td class="text-center"><img class="img-fluid"style="width: 90px; height: 90px;" src="{{ asset('uploads/photos/'~produit.photo) | default('Images/products.jpg') }}" alt="Pas de photo du produit" /></td>
                            <td class="text-center">{{ produit.getTypeProduitId().libelle | default("Aucun type renseigné")}}</td>
                            <td class="text-center">{{ produit.stock }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/produit/showProduits.html.twig
{% extends 'base.html.twig' %}
{% block header %}<h1 class="text-center">Liste des produits</h1>{% endblock %}

{% block body %}
        {% if is_granted('ROLE_ADMIN') %}
            {% for produit in produits %}
                {% if produit.stock <=10 %}
                    <div class="alert alert-danger" role="alert">
                        <tr class="table">
                            <th scope="row"><a href="{{ path('Produit.viewDetails', {id: produit.id}) }}">{{ produit.nom }}</a></th>
                            <td>{{ produit.prix }} €</td>
                            <br><td class="text-center" {% if produit.stock <=10 %} style="color: #cc0000;"{% endif %}>{% if produit.stock <=10 and produit.stock>0 %}Il ne reste plus que {{ produit.stock }} exemplaires ! {% elseif produit.stock==0 %} Ce produit n'est plus disponible ! {% else %} {{ produit.stock }} {% endif %}</td>
                            {% if is_granted('ROLE_USER') and produit.stock>0 %}
                                <td class="text-center"><a href="{{ path('Panier.addItem', {id: produit.id}) }}"><span class="icono-plus" aria-hidden="true" style="color: #21ff94;"></span></a></td>
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <td class="text-center">
                                    <a href="{{ path('produit.incremente', {id: produit.id}) }}"><span class="icono-plus" style="color: #21ff94;"></span></a>
                                    <a href="{{ path('produit.decremente', {id: produit.id}) }}"><span class="icono-cross" style="color: #cc0000;"></span></a>
                                    <a href="{{ path('Produit.remove', {id: produit.id}) }}"><span class="icono-trash" style="color: #cc0000;"></span></a>
                                </td>
                            {% endif %}
                        </tr>
                    </div>
                {% endif %}
            {% endfor %}
        <a class="btn btn-info m-1" href="{{ path('Produit.add') }}">Ajouter un produit</a>
        {% endif %}
        <div class="row text-center" style="margin-bottom: 5em;">
                        {% if produits is empty %}
                            <strong>Pas de produit disponible</strong>
                        {% endif %}
                        {% for produit in produits %}
                            <div class="card m-4 mx-auto" style="width: 18rem;">
                                <img class="card-img-top mx-auto" style="width: 90px; height: 90px" src="{{ asset('uploads/photos/'~produit.photo) | default('Images/products.jpg') }}" alt="Pas de photo du produit" />
                                <hr>
                                <div class="card-body">
                                    <h5 class="card-title"><a href="{{ path('Produit.viewDetails', {id: produit.id}) }}">{{ produit.nom }}</a></h5>
                                    <strong>{{ produit.prix }} €</strong></br>
                                    <strong>{{ produit.getTypeProduitId().libelle | default("Aucun type renseigné")}}</strong></br>
                                    <p class="card-text"{% if produit.stock <=10 %} style="color: #cc0000;"{% endif %}>{% if produit.stock <=10 and produit.stock>0 %}Il ne reste plus que {{ produit.stock }} exemplaires ! {% elseif produit.stock==0 %} Ce produit n'est plus disponible ! {% else %} {{ produit.stock }} {% endif %}</p>
                                    {% if is_granted('ROLE_USER') and produit.stock>0 %}
                                        <a href="{{ path('Panier.addItem', {id: produit.id}) }}"><span class="icono-plus" aria-hidden="true" style="color: #21ff94;"></span></a>
                                    {% endif %}
                                    {% if is_granted('ROLE_ADMIN') %}
                                            <a href="{{ path('produit.incremente', {id: produit.id}) }}"><span class="icono-plus" style="color: #21ff94;"></span></a>
                                            <a href="{{ path('produit.decremente', {id: produit.id}) }}"><span class="icono-cross" style="color: #cc0000;"></span></a>
                                            <a href="{{ path('Produit.remove', {id: produit.id}) }}"><span class="icono-trash" style="color: #cc0000;"></span></a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
        </div>
    <div class="pagination">
        {{ knp_pagination_render(produits) }}
    </div>
    <div class="row">
        {#Affichage du panier si l'utilisateur est un client #}
        {% if is_granted('ROLE_USER') %}
            <h1 class="text-center">Espace Panier</h1>
            {% include 'panier/table_panier.html.twig' %}
        {% endif %}
    </div>
{% endblock %}

templates/produit/viewDetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails{% endblock %}

{% block header %}
<h1 class="text-center">Détails du produit : {{ produit.nom }}</h1>
{% endblock %}

{% block body %}
<div class="card m-5">
    <div class="card-body text-center">
        <img  class="img-fluid" src="{{ asset('Images/'~produit.photo ) }}" alt="Photo du produit">
        <h4 class="card-title">{{ produit.nom }}</h4>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <h6>Prix : </h6>
            <p class="float-right">{{ produit.prix }}€</p>
        </li>
        <li class="list-group-item">
            <h6>Disponible : </h6>
            {% if produit.stock < 10 and produit.disponible == true %}
                <p class="text-right">Il n'en reste que {{produit.stock}}</p>
            {% elseif produit.disponible == true %}
                <span class="icono-check float-right" aria-hidden="true" style="color: #0a9816;"></span>
            {% else %}
                <span class="icono-cross float-right" aria-hidden="true" style="color: #980403;"></span>
            {% endif %}
        </li>
        <li class="list-group-item">
            <h6>Type : </h6>
            <p class="float-right">{{ produit.typeProduitId.libelle }}</p>
        </li>

    </ul>
</div>

{% for comment in produit.comments if produit.comments is not empty%}
    {% include 'comment/comment_show.html.twig' with {'comment': comment} %}
{% else %}
    <p class="text-secondary text-center" style="margin-bottom: 5em;">Pas encore de commentaires sur cette article !</p>
{% endfor %}

{% if is_granted('ROLE_USER') %}
    <div>
        {% include 'comment/form_comment.html.twig' %}
    </div>
{% endif %}
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
  $(function () {
      $('textarea.ckeditor').ckeditor();
  })
</script>
{% endblock %}